name: Release pipeline

on:
  push:
    branches:
      - main

jobs:
  release-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.9 ]

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_PROD_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.5

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project
        run: |
          pip install -r unit-requirements.txt

      # - name: Deploy PROD-telco-churn-model-train job [prod environment]
      #   run: |
      #     dbx deploy --deployment-file conf/deployment.yml --jobs=PROD-telco-churn-model-train --environment=prod

      # - name: Deploy PROD-telco-churn-model-deployment job [prod environment]
      #   run: |
      #     dbx deploy --deployment-file conf/deployment.yml --jobs=PROD-telco-churn-model-deployment --environment=prod

      - name: Deploy PROD-telco-churn-model-inference-batch job [prod environment]
        run: |
          dbx deploy --deployment-file conf/deployment.yml --jobs=PROD-telco-churn-model-inference-batch --environment=prod

      - name: Deploy e2e job [prod environment]
        run: |
          dbx deploy --deployment-file conf/deployment.yml --jobs=PROD-telco-churn-e2e --environment=prod

      - name: RUN PROD-telco-churn-e2e job [prod environment]
        run: |
          dbx launch --job=PROD-telco-churn-e2e --environment=prod --trace